espn_abbreviation_full = {
    "G": "goals",
    "A": "assist",
    "+/-": "plus_minus",
    "16": "points",
    "PIM": "penalty_minutes",
    "PPG": "power_play_goals",
    "19": "power_play_assists",
    "SHG": "short_handed_goals",
    "SHA": "short_handed_assists",
    "GWG": "game_winning_goals",
    "FOW": "faceoff_wins",
    "FOL": "faceoff_losses",
    "25": "???",
    "TTOI ?": "time_on_ice",
    "ATOI": "average_time_on_ice",
    "HAT": "hat_tricks",
    "SOG": "shots_on_goal",
    "30": "game_played",
    "HIT": "hits",
    "BLK": "blocks",
    "DEF": "defensive_points",
    "GP": "games_played",
    "35": "???",
    "36": "???",
    "37": "???",
    "PPP": "power_play_points",
    "SHP": "short_handed_points",
    "GS": "games_started",
    "W": "wins",
    "L": "losses",
    "GA": "goals_against",
    "SV": "saves",
    "SO": "shutouts",
    "OTL": "overtime_losses",
    "MIN ?": "minutes_played",
    "GAA": "goals_against_average",
    "SV%": "save_percentage"
}

espn_abbreviation_short = {
    "G": "G",
    "A": "A",
    "+/-": "P_M",
    "16": "PTS",
    "PIM": "PIM",
    "PPG": "PPG",
    "19": "PPA",
    "SHG": "SHG",
    "SHA": "SHA",
    "GWG": "GWG",
    "FOW": "FOW",
    "FOL": "FOL",
    "25": "???",
    "TTOI ?": "TTOI",
    "ATOI": "ATOI",
    "HAT": "HAT",
    "SOG": "SOG",
    "30": "GP",
    "HIT": "HIT",
    "BLK": "BLK",
    "DEF": "DEF",
    "GP": "GP",
    "35": "???",
    "36": "???",
    "37": "???",
    "PPP": "PPP",
    "SHP": "SHP",
    "GS": "GS",
    "W": "W",
    "L": "L",
    "GA": "GA",
    "SV": "SV",
    "SO": "SO",
    "OTL": "OTL",
    "MIN ?": "MIN",
    "GAA": "GAA",
    "SV%": "SVP"
}

sqlite_player_table = {
    "id": "INTEGER PRIMARY KEY",
    "name": "TEXT",
    "active": "INTEGER",
    "group": "TEXT",
    "position": "TEXT",
    "draft_pick": "INTEGER",
    "draft_keeper": "INTEGER",
    "draft_price": "INTEGER",
    "draft_cap_percentage": "REAL"
}

sqllite_league_scorting_table = {
    "G": "REAL",
    "A": "REAL",
    "+/-": "REAL",
    "16": "REAL",
    "PIM": "REAL",
    "PPG": "REAL",
    "19": "REAL",
    "SHG": "REAL",
    "SHA": "REAL",
    "GWG": "REAL",
    "FOW": "REAL",
    "FOL": "REAL",
    "25": "REAL",
    "TTOI ?": "REAL",
    "ATOI": "REAL",
    "HAT": "REAL",
    "SOG": "REAL",
    "30": "REAL",
    "HIT": "REAL",
    "BLK": "REAL",
    "DEF": "REAL",
    "GP": "REAL",
    "35": "REAL",
    "36": "REAL",
    "37": "REAL",
    "PPP": "REAL",
    "SHP": "REAL",
    "GS": "REAL",
    "W": "REAL",
    "L": "REAL",
    "GA": "REAL",
    "SV": "REAL",
    "SO": "REAL",
    "OTL": "REAL",
    "MIN ?": "REAL",
    "GAA": "REAL",
    "SV%": "REAL"
}

sqlite_skater_forwards_stats_table = {
    "id": "INTEGER PRIMARY KEY",
    "year": "INTEGER",
    "stats_type": "TEXT",
    "G": "REAL",
    "A": "REAL",
    "P_M": "REAL",
    "PTS": "REAL",
    "PIM": "REAL",
    "PPG": "REAL",
    "PPA": "REAL",
    "SHG": "REAL",
    "SHA": "REAL",
    "GWG": "REAL",
    "FOW": "REAL",
    "FOL": "REAL",
    "TTOI": "REAL",
    "ATOI": "REAL",
    "HAT": "REAL",
    "SOG": "REAL",
    "GP": "REAL",
    "HIT": "REAL",
    "BLK": "REAL"
}

sqlite_skater_defenceman_stats_table = {
    "id": "INTEGER PRIMARY KEY",
    "year": "INTEGER",
    "stats_type": "TEXT",
    "G": "REAL",
    "A": "REAL",
    "P_M": "REAL",
    "PTS": "REAL",
    "PIM": "REAL",
    "PPG": "REAL",
    "PPA": "REAL",
    "SHG": "REAL",
    "SHA": "REAL",
    "GWG": "REAL",
    "FOW": "REAL",
    "FOL": "REAL",
    "TTOI": "REAL",
    "ATOI": "REAL",
    "HAT": "REAL",
    "SOG": "REAL",
    "GP": "REAL",
    "HIT": "REAL",
    "BLK": "REAL",
    "DEF": "REAL"
}

sqlite_goalie_stats_table = {
    "id": "INTEGER PRIMARY KEY",
    "year": "INTEGER",
    "stats_type": "TEXT",
    "GS": "REAL",
    "W": "REAL",
    "L": "REAL",
    "GA": "REAL",
    "SV": "REAL",
    "SO": "REAL",
    "OTL": "REAL",
    "MIN": "REAL",
    "GAA": "REAL",
    "SVP": "REAL"
}